# Generated by Django 3.2.12 on 2023-07-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bimg',
            field=models.TextField(default='The Django web framework is a free, open source framework that can speed up development of a web application being built in the Python programming language. Django—pronounced “Jango,” named after the famous jazz guitarist Django Reinhardt—is a free, open source framework that was first publicly released in 2005.'),
            preserve_default=False,
        ),
    ]
