# Generated by Django 3.2.12 on 2023-07-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_bimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bimg',
            new_name='bdesc',
        ),
        migrations.AddField(
            model_name='book',
            name='bprice',
            field=models.IntegerField(default=500),
        ),
    ]
